title: demo1
description: 试试水，学习怎么使用git
template:
  repo: demo1-template
  name: demo1
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
